-- ==========================================
-- SUPABASE COMPLETE SCHEMA - NETPLAY
-- ==========================================

-- 1. Movies Table
CREATE TABLE IF NOT EXISTS movies (
    id BIGINT PRIMARY KEY, -- TMDb ID
    title TEXT,
    name TEXT,
    original_name TEXT,
    backdrop_path TEXT,
    poster_path TEXT,
    logo_path TEXT,
    overview TEXT,
    first_air_date TEXT,
    release_date TEXT,
    vote_average DECIMAL(3,1),
    video_url TEXT,
    video_url_2 TEXT,
    file_name TEXT,
    genres TEXT,
    type TEXT CHECK (type IN ('movie', 'series')),
    actors TEXT,
    rating DECIMAL(3,1),
    runtime INTEGER,
    release_year INTEGER,
    watch_providers TEXT,
    last_rescanned_at TIMESTAMPTZ,
    is_hidden BOOLEAN DEFAULT FALSE,
    collection_id BIGINT,
    collection_name TEXT,
    collection_poster_path TEXT,
    collection_logo_path TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Streaming Providers
CREATE TABLE IF NOT EXISTS streaming_providers (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    logo_url TEXT,
    priority INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Admin Users (Whitelist)
CREATE TABLE IF NOT EXISTS admin_users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Pre-seed admin user
INSERT INTO admin_users (email) VALUES ('costachristopher31@gmail.com') ON CONFLICT (email) DO NOTHING;

-- 4. User Profiles (Multi-profile support)
CREATE TABLE IF NOT EXISTS profiles (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Watch History (Progress tracking)
CREATE TABLE IF NOT EXISTS watch_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    movie_id BIGINT REFERENCES movies(id) ON DELETE CASCADE,
    last_position DECIMAL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(profile_id, movie_id)
);

-- 6. My List (Favorites/Bookmarks)
CREATE TABLE IF NOT EXISTS my_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    movie_id BIGINT REFERENCES movies(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(profile_id, movie_id)
);

-- 7. App Settings
CREATE TABLE IF NOT EXISTS app_settings (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    theme TEXT DEFAULT 'dark',
    language TEXT DEFAULT 'pt-BR',
    autoplay_next BOOLEAN DEFAULT TRUE,
    show_logos BOOLEAN DEFAULT TRUE,
    subscription_plan TEXT,
    subscription_status TEXT CHECK (subscription_status IN ('active', 'pending', 'expired')),
    subscription_expires_at TIMESTAMPTZ,
    google_drive_token TEXT,
    google_drive_accounts JSONB DEFAULT '[]'::jsonb,
    category_backdrops JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- AUTHENTICATION TRIGGERS
-- ==========================================

-- Function to handle new user creation
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  -- Create default profile for the user if it doesn't exist
  INSERT INTO public.profiles (user_id, name, avatar_url)
  VALUES (new.id, COALESCE(split_part(new.email, '@', 1), 'Usuário'), 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Netflix-avatar.png')
  ON CONFLICT DO NOTHING;

  -- Create default app settings if they don't exist
  INSERT INTO public.app_settings (user_id)
  VALUES (new.id)
  ON CONFLICT DO NOTHING;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Trigger to call the function after a user signs up
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- ROW LEVEL SECURITY (RLS)
-- ==========================================

ALTER TABLE movies ENABLE ROW LEVEL SECURITY;
ALTER TABLE streaming_providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE watch_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE my_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;

-- Movies: Public Read
CREATE POLICY "Public Read Movies" ON movies FOR SELECT USING (true);
CREATE POLICY "Admin All Movies" ON movies FOR ALL USING (
    EXISTS (SELECT 1 FROM admin_users WHERE email = auth.email())
);

-- Providers: Public Read
CREATE POLICY "Public Read Providers" ON streaming_providers FOR SELECT USING (true);
CREATE POLICY "Admin All Providers" ON streaming_providers FOR ALL USING (
    EXISTS (SELECT 1 FROM admin_users WHERE email = auth.email())
);

-- Profiles: User can manage own
CREATE POLICY "User Manage Own Profiles" ON profiles FOR ALL USING (auth.uid() = user_id);

-- Settings: User can manage own
CREATE POLICY "User Manage Own Settings" ON app_settings FOR ALL USING (auth.uid() = user_id);

-- Watch History: User can manage via profiles
CREATE POLICY "User Manage Own History" ON watch_history FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = watch_history.profile_id AND profiles.user_id = auth.uid())
);

-- My List: User can manage via profiles
CREATE POLICY "User Manage Own List" ON my_list FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = my_list.profile_id AND profiles.user_id = auth.uid())
);

-- Admin Users: Allow authenticated users to see the list (to check if they are admins)
CREATE POLICY "Enable read for authenticated users" ON admin_users
FOR SELECT TO authenticated
USING (true);

